-- =============================================================================
-- Prosody Main Configuration (prosody.cfg.lua)
--
-- This is the global Prosody configuration file. VirtualHost-specific
-- settings live in /etc/prosody/conf.d/serverA.local.cfg.lua.
--
-- Key architectural decisions reflected here:
--   - Storage: PostgreSQL via mod_storage_sql (same DB as Node API for unified ops)
--   - No anonymous access: all auth via PLAIN (from our provisioned accounts)
--   - EC-7: XEP-0199 ping enabled with aggressive timeouts for dead connection detection
--   - mod_offline DISABLED: we use MAM pull-model, not per-user queues (EC-3)
--   - mod_register DISABLED: registration handled by Node API exclusively
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Network and Security
-- ---------------------------------------------------------------------------

-- Listen on all interfaces (Docker internal network + exposed ports)
interfaces = { "*" }

-- Administrative JIDs — only these JIDs can call mod_admin_rest endpoints.
-- The Prosody admin JID must match PROSODY_ADMIN_USER@XMPP_DOMAIN in .env.
admins = { "admin@servera.local" }

-- Use full certificate checking for S2S (federation) when it's enabled.
-- c2s (client) connections use the self-signed cert generated by our entrypoint.
s2s_secure_auth = false -- Phase 1: relaxed for self-signed certs

-- ---------------------------------------------------------------------------
-- Modules (global — loaded for all virtual hosts)
-- ---------------------------------------------------------------------------
modules_enabled = {
  -- Core XMPP functionality
  "roster",           -- Contact list management
  "saslauth",         -- SASL authentication (PLAIN mechanism for our provisioned accounts)
  "tls",              -- TLS encryption for c2s connections
  "dialback",         -- DNS-based authentication for s2s (Phase 2)
  "disco",            -- Service discovery (XEP-0030)
  "carbons",          -- Message carbons (XEP-0280) — multi-device delivery

  -- Connection management
  "ping",             -- EC-7: XEP-0199 keepalive/dead-connection detection
  "time",             -- Server time (XEP-0202)
  "version",          -- Version reporting (XEP-0092)

  -- WebSocket transport (browser clients connect via Nginx proxy)
  "websocket",        -- WebSocket support (XEP-0206)
  "bosh",             -- BOSH transport (fallback for older clients)

  -- Message archive
  "mam",              -- Message Archive Management (XEP-0313) — EC-3 pull model

  -- User profiles
  "vcard4",           -- vCard user profiles (XEP-0292) — built into Prosody 13.x
  "vcard_legacy",     -- vCard backward compatibility (XEP-0054) — community module

  "admin_rest",

  -- Logging (to stdout for Docker log aggregation)
  "posix",            -- POSIX process management
}

-- Bind HTTP to all interfaces so other Docker containers can reach it
http_interfaces = { "*" }
https_interfaces = { "*" }

-- Modules explicitly disabled
modules_disabled = {
  -- EC-3: No per-user offline queues — we use MAM timestamp-pull instead
  "offline",

  -- Registration is handled exclusively by the Node API
  "register",

  -- In-band registration must be disabled (security requirement)
  "register_ibr",
}

-- ---------------------------------------------------------------------------
-- Authentication
-- ---------------------------------------------------------------------------

-- Use Prosody's native database storage for account credentials.
-- Accounts are provisioned by the Node API via mod_admin_rest.
authentication = "internal_hashed"

-- ---------------------------------------------------------------------------
-- Storage Backend: PostgreSQL
-- ---------------------------------------------------------------------------
-- All persistent data (message archives, rosters, accounts) is stored in
-- the same PostgreSQL instance used by the Node API.
-- This allows direct SQL queries for MAM history from the API (EC-5, EC-8).

storage = "sql"

sql = {
  driver   = "PostgreSQL",
  database = os.getenv("POSTGRES_DB")       or "slackathon",
  username = os.getenv("POSTGRES_USER")     or "slackathon",
  password = os.getenv("POSTGRES_PASSWORD") or "changeme",
  host     = os.getenv("POSTGRES_HOST")     or "postgres",
  port     = 5432,
}

-- ---------------------------------------------------------------------------
-- EC-7: Dead Connection Handling (XEP-0199 Ping / Hibernation)
--
-- Browser tabs can be hibernated by the OS, suspending JS execution.
-- Without server-side ping, hibernated clients appear online indefinitely.
-- With these settings, a dead connection is detected within 45 seconds
-- (30s ping interval + 15s pong timeout) and forcefully closed.
-- Prosody then broadcasts <presence type="unavailable"/> to all rooms.
-- ---------------------------------------------------------------------------
c2s_timeout = 60          -- Forcefully close connections that have been idle 60s
                          -- (covers the 30+15s ping cycle with buffer)

-- mod_ping configuration (community module)
-- ping_interval and ping_timeout are set in the VirtualHost config below
-- for clarity, but could also be set globally here.

-- ---------------------------------------------------------------------------
-- WebSocket configuration
-- ---------------------------------------------------------------------------

-- Cross-origin policy for WebSocket connections
-- In development, allow all origins. In production, restrict to app domain.
cross_domain_websocket = true
consider_websocket_secure = true -- Trust the x-forwarded-proto header from Nginx

-- ---------------------------------------------------------------------------
-- BOSH configuration (fallback, not primary transport)
-- ---------------------------------------------------------------------------
cross_domain_bosh = true
bosh_max_inactivity = 60

-- ---------------------------------------------------------------------------
-- Message Archive Management (MAM — XEP-0313)
-- ---------------------------------------------------------------------------

-- Archive all messages by default (users can opt out per-conversation)
archive_expires_after = "never"  -- Store messages indefinitely (per requirements)

-- Default policy: archive all messages
default_archive_policy = true

-- ---------------------------------------------------------------------------
-- Logging
-- ---------------------------------------------------------------------------
-- Log to stdout so Docker captures all output via `docker logs` or log drivers.
-- In production, consider "info" level to reduce noise.

log = {
  { levels = { min = "info" }, to = "stdout" },
  { levels = { min = "error" }, to = "stderr" },
}

-- ---------------------------------------------------------------------------
-- TLS / Certificate Paths
-- ---------------------------------------------------------------------------
certificates = "/etc/prosody/certs"

-- ---------------------------------------------------------------------------
-- mod_admin_rest configuration
-- ---------------------------------------------------------------------------
admin_rest_base_path = "/admin_rest"
admin_rest_secure = false   -- HTTP only (internal Docker network)

-- ---------------------------------------------------------------------------
-- Load VirtualHost configurations from conf.d/
-- This must be at the very bottom of the main config file.
-- ---------------------------------------------------------------------------
Include "conf.d/*.cfg.lua"

VirtualHost "prosody"
